services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service

  author-service:
    build: ./author-service
    container_name: author-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service

  genre-service:
    build: ./genre-service
    container_name: genre-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery-service

  userbook-service:
    build: ./userbook-service
    container_name: userbook-service
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service


volumes:

